TRAIN:
  ENABLE: True ##
  DATASET: charades
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#   CHECKPOINT_FILE_PATH: # please download from the model zoo. 
  CHECKPOINT_TYPE: pytorch #caffe2
  CHECKPOINT_INFLATE: False #True
DATA:
  NUM_FRAMES: 8 #64
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 340]
  TRAIN_CROP_SIZE: 256 #224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: data/ak/annot ## annotation 
  PATH_PREFIX: data/ak/image ## images 
  DECODING_BACKEND: torchvision

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1 #4
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.05 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 2 #200 #256
  LR_POLICY: cosine
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
  
MODEL:
  NUM_CLASSES: 140
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: EQL ## bce_loss, focal_loss, LDAM, EQL ##
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True ##
  DATASET: charades
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3
#   CHECKPOINT_FILE_PATH: .
  CHECKPOINT_TYPE: pytorch
  SAVE_RESULTS_PATH: ./results/i3d ##
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
NUM_GPUS: 1 #8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./logs/x3d-l
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: False
