TRAIN:
  ENABLE: True ##
  DATASET: charades
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
#   CHECKPOINT_FILE_PATH: # please download from the model zoo. 
  CHECKPOINT_TYPE: pytorch #caffe2
  CHECKPOINT_INFLATE: False #True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 340]
  TRAIN_CROP_SIZE: 256 #224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: data/ak/annot ## annotation
  PATH_PREFIX: data/ak/image ## images 
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 100
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1 #4
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 100 ##
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 140
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: focal_loss ## bce_loss, focal_loss, LDAM, EQL ##
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True ###
  DATASET: charades
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
#   CHECKPOINT_FILE_PATH: .
  CHECKPOINT_TYPE: pytorch
  SAVE_RESULTS_PATH: ./results/i3d ##
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
NUM_GPUS: 2 #8 ##
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./logs/i3d
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: False
